OPTIONS = {
    "business_identification_system": {
        "legal_entity_identifier": "Legal Entity Identifier (LEI)", 
        "bureau_van_dijk": "Bureau van Dijk"
    },

    "country_list": {
        "argentina": "Argentina",
        "australia": "Australia",
        "austria": "Austria",
        "belgium": "Belgium",
        "brazil": "Brazil",
        "brunei_darussalam": "Brunei Darussalam",
        "bulgaria": "Bulgaria",
        "cambodia": "Cambodia",
        "canada": "Canada",
        "chile": "Chile",
        "china": "China",
        "colombia": "Colombia",
        "costa_rica": "Costa Rica",
        "croatia": "Croatia",
        "cyprus": "Cyprus",
        "czech_republic": "Czech Republic",
        "denmark": "Denmark",
        "estonia": "Estonia",
        "finland": "Finland",
        "france": "France",
        "germany": "Germany",
        "greece": "Greece",
        "hong_kong": "Hong Kong",
        "hungary": "Hungary",
        "iceland": "Iceland",
        "india": "India",
        "indonesia": "Indonesia",
        "ireland": "Ireland",
        "israel": "Israel",
        "italy": "Italy",
        "japan": "Japan",
        "kazakhstan": "Kazakhstan",
        "republic_of_korea": "Republic of Korea",
        "latvia": "Latvia",
        "liechtenstein": "Liechtenstein",
        "lithuania": "Lithuania",
        "luxembourg": "Luxembourg",
        "malaysia": "Malaysia",
        "malta": "Malta",
        "mexico": "Mexico",
        "morocco": "Morocco",
        "netherlands": "Netherlands",
        "new_zealand": "New Zealand",
        "norway": "Norway",
        "peru": "Peru",
        "philippines": "Philippines",
        "poland": "Poland",
        "portugal": "Portugal",
        "rest_of_world": "Rest of World",
        "romania": "Romania",
        "russian_federation": "Russian Federation",
        "saudi_arabia": "Saudi Arabia",
        "singapore": "Singapore",
        "slovak_republic": "Slovak Republic",
        "slovenia": "Slovenia",
        "south_africa": "South Africa",
        "spain": "Spain",
        "sweden": "Sweden",
        "switzerland": "Switzerland",
        "taiwan": "Taiwan",
        "thailand": "Thailand",
        "tunisia": "Tunisia",
        "turkey": "Turkey",
        "united_kingdom": "United Kingdom",
        "united_states": "United States",
        "vietnam": "Vietnam"
    },


    "decarbonisation_strategy": {
        "board_oversight": "Yes, with board oversight",
        "yes_without_board_oversight": "Yes, but without board oversight",
        "no": "No"
    },

    "ems_presence_select": {
        "yes_iso_14001_certified": "Yes (ISO 14001 certified)",
        "yes_other_ems_certification": "Yes (other EMS certification)",
        "yes_without_certification": "Yes (without certification)",
        "no": "No, not in place",
    },

    "eu_country_list": {
        "austria": "Austria",
        "belgium": "Belgium",
        "bulgaria": "Bulgaria",
        "croatia": "Croatia",
        "cyprus": "Cyprus",
        "czech_republic": "Czech Republic",
        "denmark": "Denmark",
        "estonia": "Estonia",
        "finland": "Finland",
        "france": "France",
        "germany": "Germany",
        "greece": "Greece",
        "hungary": "Hungary",
        "ireland": "Ireland",
        "italy": "Italy",
        "latvia": "Latvia",
        "lithuania": "Lithuania",
        "luxembourg": "Luxembourg",
        "malta": "Malta",
        "netherlands": "Netherlands",
        "poland": "Poland",
        "portugal": "Portugal",
        "romania": "Romania",
        "slovak_republic": "Slovak Republic",
        "slovenia": "Slovenia",
        "spain": "Spain",
        "sweden": "Sweden"
    },


    "ghg_reduction_target": {
        "no": "No",
        "yes_not_paris": "Yes, but it is not Paris-aligned",
        "yes_paris": "Yes, and it is Paris–aligned (covering Scope 1, 2, & material Scope 3)",
    },

    "ghg_scope_list": {
        "scope_1": "Yes — GHG Protocol Scope 1",
        "scope_1_2": "Yes - GHG Protocol Scope 1 and 2",
        "scope_1_2_3": "Yes - GHG Protocol Scope 1, 2, and 3",
        "other_protocol": "Yes - Other than GHG Protocol",
        "no": "No",
    },

    "ghg_scope_1_methodology": {
        "spend_based": "Spend-based",
        "activity_based": "Activity-based",
        "direct_monitoring": "Direct monitoring",
        "other": "Other",
    },

    "ghg_scope_2_methodology": {
        "location_based": "Location-based",
        "market_based": "Market-based",
        "unspecified": "Unspecified",
    },

    "ghg_scope_3_methodology": {
        "spend_based": "Spend-based",
        "activity_based": "Activity-based",
        "direct_emissions_supplier_based": "Direct emissions/supplier-based",
        "other": "Other",
    },

    "iso_currency_code": {
        "AED": "UAE Dirham",
        "AFN": "Afghani",
        "ALL": "Lek",
        "AMD": "Armenian Dram",
        "ANG": "Netherlands Antillean Guilder",
        "AOA": "Kwanza",
        "ARS": "Argentine Peso",
        "AUD": "Australian Dollar",
        "AWG": "Aruban Florin",
        "AZN": "Azerbaijan Manat",
        "BAM": "Convertible Mark",
        "BBD": "Barbados Dollar",
        "BDT": "Taka",
        "BGN": "Bulgarian Lev",
        "BHD": "Bahraini Dinar",
        "BIF": "Burundi Franc",
        "BMD": "Bermudian Dollar",
        "BND": "Brunei Dollar",
        "BOB": "Boliviano",
        "BOV": "Mvdol",
        "BRL": "Brazilian Real",
        "BSD": "Bahamian Dollar",
        "BTN": "Ngultrum",
        "BWP": "Pula",
        "BYN": "Belarusian Ruble",
        "BZD": "Belize Dollar",
        "CAD": "Canadian Dollar",
        "CDF": "Congolese Franc",
        "CHE": "WIR Euro",
        "CHF": "Swiss Franc",
        "CHW": "WIR Franc",
        "CLF": "Unidad de Fomento",
        "CLP": "Chilean Peso",
        "CNY": "Yuan Renminbi",
        "COP": "Colombian Peso",
        "COU": "Unidad de Valor Real",
        "CRC": "Costa Rican Colon",
        "CUC": "Peso Convertible",
        "CUP": "Cuban Peso",
        "CVE": "Cabo Verde Escudo",
        "CZK": "Czech Koruna",
        "DJF": "Djibouti Franc",
        "DKK": "Danish Krone",
        "DOP": "Dominican Peso",
        "DZD": "Algerian Dinar",
        "EGP": "Egyptian Pound",
        "ERN": "Nakfa",
        "ETB": "Ethiopian Birr",
        "EUR": "Euro",
        "FJD": "Fiji Dollar",
        "FKP": "Falkland Islands Pound",
        "GBP": "Pound Sterling",
        "GEL": "Lari",
        "GHS": "Ghana Cedi",
        "GIP": "Gibraltar Pound",
        "GMD": "Dalasi",
        "GNF": "Guinean Franc",
        "GTQ": "Quetzal",
        "GYD": "Guyana Dollar",
        "HKD": "Hong Kong Dollar",
        "HNL": "Lempira",
        "HTG": "Gourde",
        "HUF": "Forint",
        "IDR": "Rupiah",
        "ILS": "New Israeli Sheqel",
        "INR": "Indian Rupee",
        "IQD": "Iraqi Dinar",
        "IRR": "Iranian Rial",
        "ISK": "Iceland Krona",
        "JMD": "Jamaican Dollar",
        "JOD": "Jordanian Dinar",
        "JPY": "Yen",
        "KES": "Kenyan Shilling",
        "KGS": "Som",
        "KHR": "Riel",
        "KMF": "Comorian Franc",
        "KPW": "North Korean Won",
        "KRW": "Won",
        "KWD": "Kuwaiti Dinar",
        "KYD": "Cayman Islands Dollar",
        "KZT": "Tenge",
        "LAK": "Lao Kip",
        "LBP": "Lebanese Pound",
        "LKR": "Sri Lanka Rupee",
        "LRD": "Liberian Dollar",
        "LSL": "Loti",
        "LYD": "Libyan Dinar",
        "MAD": "Moroccan Dirham",
        "MDL": "Moldovan Leu",
        "MGA": "Malagasy Ariary",
        "MKD": "Denar",
        "MMK": "Kyat",
        "MNT": "Tugrik",
        "MOP": "Pataca",
        "MRU": "Ouguiya",
        "MUR": "Mauritius Rupee",
        "MVR": "Rufiyaa",
        "MWK": "Malawi Kwacha",
        "MXN": "Mexican Peso",
        "MXV": "Mexican Unidad de Inversion (UDI)",
        "MYR": "Malaysian Ringgit",
        "MZN": "Mozambique Metical",
        "NAD": "Namibia Dollar",
        "NGN": "Naira",
        "NIO": "Cordoba Oro",
        "NOK": "Norwegian Krone",
        "NPR": "Nepalese Rupee",
        "NZD": "New Zealand Dollar",
        "OMR": "Rial Omani",
        "PAB": "Balboa",
        "PEN": "Sol",
        "PGK": "Kina",
        "PHP": "Philippine Peso",
        "PKR": "Pakistan Rupee",
        "PLN": "Zloty",
        "PYG": "Guarani",
        "QAR": "Qatari Rial",
        "RON": "Romanian Leu",
        "RSD": "Serbian Dinar",
        "RUB": "Russian Ruble",
        "RWF": "Rwanda Franc",
        "SAR": "Saudi Riyal",
        "SBD": "Solomon Islands Dollar",
        "SCR": "Seychelles Rupee",
        "SDG": "Sudanese Pound",
        "SEK": "Swedish Krona",
        "SGD": "Singapore Dollar",
        "SHP": "Saint Helena Pound",
        "SLE": "Leone",
        "SOS": "Somali Shilling",
        "SRD": "Surinam Dollar",
        "SSP": "South Sudanese Pound",
        "STN": "Dobra",
        "SVC": "El Salvador Colon",
        "SYP": "Syrian Pound",
        "SZL": "Lilangeni",
        "THB": "Baht",
        "TJS": "Somoni",
        "TMT": "Turkmenistan New Manat",
        "TND": "Tunisian Dinar",
        "TOP": "Pa’anga",
        "TRY": "Turkish Lira",
        "TTD": "Trinidad and Tobago Dollar",
        "TWD": "New Taiwan Dollar",
        "TZS": "Tanzanian Shilling",
        "UAH": "Hryvnia",
        "UGX": "Uganda Shilling",
        "USD": "US Dollar",
        "USN": "US Dollar (Next day)",
        "UYI": "Uruguay Peso en Unidades Indexadas (UI)",
        "UYU": "Peso Uruguayo",
        "UYW": "Unidad Previsional",
        "UZS": "Uzbekistan Sum",
        "VED": "Bolívar Soberano",
        "VES": "Bolívar Soberano",
        "VND": "Dong",
        "VUV": "Vatu",
        "WST": "Tala",
        "XAF": "CFA Franc BEAC",
        "XAG": "Silver",
        "XAU": "Gold",
        "XBA": "Bond Markets Unit European Composite Unit (EURCO)",
        "XBB": "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
        "XBC": "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
        "XBD": "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
        "XCD": "East Caribbean Dollar",
        "XDR": "SDR (Special Drawing Right)",
        "XOF": "CFA Franc BCEAO",
        "XPD": "Palladium",
        "XPF": "CFP Franc",
        "XPT": "Platinum",
        "XSU": "Sucre",
        "XTS": "Codes specifically reserved for testing purposes",
        "XUA": "ADB Unit of Account",
        "XXX": "The codes assigned for transactions where no currency is involved",
        "YER": "Yemeni Rial",
        "ZAR": "Rand",
        "ZMW": "Zambian Kwacha",
        "ZWG": "Zimbabwe Gold"
    },

    "long_term_net_zero_goal": {
        "no_plan": "No - and no plan to set one (e.g. lack of viable pathway)",
        "no_establish_soon": "No - but we plan to establish this in the near term (<2 years)",
        "no_a_goal_but_not_net_zero": "No - we have a long-term goal but not fully aligned with a net zero pathway (i.e., NZ emissions by 2050 or sooner)",
        "yes": "Yes - aligned with a net zero pathway (i.e., NZ emissions by 2050 or sooner)",
    },

    "nace_divisions": {
        "crop_animal_production_services": "01 Crop and animal production, hunting and related service activities (en)",
        "forestry_logging": "02 Forestry and logging (en)",
        "fishing_aquaculture": "03 Fishing and aquaculture (en)",
        "mining_coal_lignite": "05 Mining of coal and lignite (en)",
        "extraction_crude_petroleum_natural_gas": "06 Extraction of crude petroleum and natural gas (en)",
        "mining_metal_ores": "07 Mining of metal ores (en)",
        "other_mining_quarrying": "08 Other mining and quarrying (en)",
        "mining_support": "09 Mining support service activities (en)",
        "manufacture_food": "10 Manufacture of food products (en)",
        "manufacture_beverages": "11 Manufacture of beverages (en)",
        "manufacture_tobacco_products": "12 Manufacture of tobacco products (en)",
        "manufacture_textiles": "13 Manufacture of textiles (en)",
        "manufacture_wearing_apparel": "14 Manufacture of wearing apparel (en)",
        "manufacture_leather": "15 Manufacture of leather and related products of other materials (en)",
        "manufacture_wood": "16 Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials (en)",
        "manufacture_paper_products": "17 Manufacture of paper and paper products (en)",
        "printing_reproduction_recorded_media": "18 Printing and reproduction of recorded media (en)",
        "manufacture_coke_refined_petroleum_products": "19 Manufacture of coke and refined petroleum products (en)",
        "manufacture_chemicals_chemical_products": "20 Manufacture of chemicals and chemical products (en)",
        "manufacture_basic_pharmaceutical_and_preparations": "21 Manufacture of basic pharmaceutical products and pharmaceutical preparations (en)",
        "manufacture_rubber_plastic_products": "22 Manufacture of rubber and plastic products (en)",
        "manufacture_other_nonmetallic_mineral_products": "23 Manufacture of other non-metallic mineral products (en)",
        "manufacture_basic_metals": "24 Manufacture of basic metals (en)",
        "manufacture_fabricated_metal": "25 Manufacture of fabricated metal products, except machinery and equipment (en)",
        "manufacture_computer_electronic_optical": "26 Manufacture of computer, electronic and optical products (en)",
        "manufacture_electrical_equipment": "27 Manufacture of electrical equipment (en)",
        "manufacture_machinery_equipment": "28 Manufacture of machinery and equipment n.e.c. (en)",
        "manufacture_mvs": "29 Manufacture of motor vehicles, trailers and semi-trailers (en)",
        "manufacture_other_transport_equipment": "30 Manufacture of other transport equipment (en)",
        "manufacture_furniture": "31 Manufacture of furniture (en)",
        "other_manufacturing": "32 Other manufacturing (en)",
        "repair_installation_machinery_equipment": "33 Repair, maintenance and installation of machinery and equipment (en)",
        "electricity_gas_steam_ac_supply": "35 Electricity, gas, steam and air conditioning supply (en)",
        "water_collection_treatment_supply": "36 Water collection, treatment and supply (en)",
        "sewerage": "37 Sewerage (en)",
        "waste_collection_treatment_disposal_materials_recovery": "38 Waste collection, recovery and disposal activities (en)",
        "remediation_waste_management_services": "39 Remediation activities and other waste management service activities (en)",
        "construction_buildings": "41 Construction of residential and non-residential buildings (en)",
        "civil_engineering": "42 Civil engineering (en)",
        "specialised_construction": "43 Specialised construction activities (en)",
        "wholesale_trade": "46 Wholesale trade (en)",
        "retail_trade": "47 Retail trade (en)",
        "land_and_viapipeline_transport": "49 Land transport and transport via pipelines (en)",
        "water_transport": "50 Water transport (en)",
        "air_transport": "51 Air transport (en)",
        "warehousing_transportation": "52 Warehousing, storage and support activities for transportation (en)",
        "postal_courier": "53 Postal and courier activities (en)",
        "accommodation": "55 Accommodation (en)",
        "food_beverage_service": "56 Food and beverage service activities (en)",
        "publishing": "58 Publishing activities (en)",
        "motion_video_tv_sound": "59 Motion picture, video and television programme production, sound recording and music publishing activities (en)",
        "programming_broadcasting": "60 Programming, broadcasting, news agency and other content distribution activities (en)",
        "telecommunications": "61 Telecommunication (en)",
        "computer_programming_consultancy": "62 Computer programming, consultancy and related activities (en)",
        "information_services": "63 Computing infrastructure, data processing, hosting and other information service activities (en)",
        "financial_services": "64 Financial service activities, except insurance and pension funding (en)",
        "insurance_reinsurance_pension": "65 Insurance, reinsurance and pension funding, except compulsory social security (en)",
        "activities_auxiliary_financial_services_insurance": "66 Activities auxiliary to financial services and insurance activities (en)",
        "real_estate": "68 Real estate activities (en)",
        "legal_accounting": "69 Legal and accounting activities (en)",
        "head_offices": "70 Activities of head offices and management consultancy (en)",
        "architectural_engineering": "71 Architectural and engineering activities; technical testing and analysis (en)",
        "scientific_research_development": "72 Scientific research and development (en)",
        "advertising_market_research": "73 Activities of advertising, market research and public relations (en)",
        "other_professional_scientific_technical": "74 Other professional, scientific and technical activities (en)",
        "veterinary": "75 Veterinary activities (en)",
        "rental_leasing": "77 Rental and leasing activities (en)",
        "employment": "78 Employment activities (en)",
        "travel": "79 Travel agency, tour operator and other reservation service and related activities (en)",
        "security_investigation": "80 Investigation and security activities (en)",
        "services_buildings_landscape": "81 Services to buildings and landscape activities (en)",
        "office_administrative_office_business_support": "82 Office administrative, office support and other business support activities (en)",
        "public_administration_defence_compulsory_socials": "84 Public administration and defence; compulsory social security (en)",
        "education": "85 Education (en)",
        "human_health": "86 Human health activities (en)",
        "residential_care": "87 Residential care activities (en)",
        "social_work": "88 Social work activities without accommodation (en)",
        "creative_arts_entertainment": "90 Arts creation and performing arts activities (en)",
        "cultural": "91 Libraries, archives, museums and other cultural activities (en)",
        "gambling_betting": "92 Gambling and betting activities (en)",
        "recreation": "93 Sports activities and amusement and recreation activities (en)",
        "membership_organisations": "94 Activities of membership organisations (en)",
        "repair_computers_personal_household_goods": "95 Repair and maintenance of computers, personal and household goods, and motor vehicles and motorcycles (en)",
        "other_personal_services": "96 Personal service activities (en)",
        "households_employers_domestic_personnel": "97 Activities of households as employers of domestic personnel (en)",
        "undifferentiated_goods_services_private_households": "98 Undifferentiated goods- and service-producing activities of private households for own use (en)",
        "extraterritorial_organisations_bodies": "99 Activities of extraterritorial organisations and bodies (en)"
    },

    "whistleblower_procedure": {
        "yes_eu_aligned": "Yes (aligned with the EU Whistleblower Directive)",
        "yes_not_eu_aligned": "Yes (not aligned with the EU Whistleblower Directive)",
        "no": "No",
        "no_but_a_plan": "No (but plan to in the next 12 months)",
    },

    "violations_ungc_oecd_guidelines": {
        "oecd_guidelines_for_multinational_enterprises": "OECD Guidelines for Multinational Enterprises",
        "un_guiding_principles_on_business_human_rights": "UNGC Guiding Principles on Business and Human Rights",
        "both": "Both OECD and UNGC",
    },

    "yes_no_expanded": {
        "yes": "Yes",
        "no": "No",
        "no_but_a_plan": "No but plan to in the next 12 months",
    },
}
